name: Build And Test
on: [push]
jobs:
  build-${{matrix.spark-version}}:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spark-version: ["2.4.7", "3.1.2"]
    name: Build Spark ${{ matrix.spark-version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Build using Python
        working-directory: Modules/matlab-spark-api/Software/Java/SparkUtility
        run: python build_jar.py -r ${{matrix.spark-version}}
          
