name: Build And Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spark-version: ["2.2.0", "2.4.5", "2.4.7", "3.0.1", "3.0.1-hadoop3.2", "3.1.2"]
        matlab-release: ["R2021a","R2021b"]
    name: MATLAB ${{ matrix.matlab-release }} Spark ${{ matrix.spark-version }}        
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab-release }}
      - name: Build using MATLAB
        uses: matlab-actions/run-command@v1
        with:
          command: "run('Software/MATLAB/startup.m'); C = matlab.sparkutils.Config.getInMemoryConfig(); C.CurrentVersion = \"${{ matrix.spark-version }}\"; C.saveConfig; buildMatlabSparkUtility(); generateJavapathForSpark(); copyfile('Software/MATLAB/javaclasspath.txt', '.');"
      - name: Test using MATLAB
        uses: matlab-actions/run-command@v1
        with:
          command: "run('Software/MATLAB/startup.m'); cd 'Software/MATLAB/test'; runCITests('${{matrix.spark-version}}-${{matrix.matlab-release}}')"        
      - name: Store Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/*.xml      
  report:
    if: ${{ success() || failure() }}
    needs: build
    runs-on: ubuntu-latest
    name: Test Report
    steps:          
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true   
      - name: Gather results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: test-results
      - name: Create report
        uses: dorny/test-reporter@v1.5.0
        with:
          name: Final Test Report
          path: test-results/*.xml 
          reporter: java-junit